from .ARCC import ARCC
from .ARCE import ARCE
from .BBH import BBH
from .BoolQ import BoolQ
from .Hellaswag import Hellaswag
from .MathQA import MathQA
from .MMLUPro import MMLUPro
from .Piqa import Piqa
from .Winogrande import Winogrande